//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using FileStream.HelperClasses;
using FileStream.FactoryClasses;
using FileStream.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace FileStream.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Attachment'.<br/><br/></summary>
	[Serializable]
	public partial class AttachmentEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static AttachmentEntityStaticMetaData _staticMetaData = new AttachmentEntityStaticMetaData();
		private static AttachmentRelations _relationsFactory = new AttachmentRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AttachmentEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AttachmentEntityStaticMetaData()
			{
				SetEntityCoreInfo("AttachmentEntity", InheritanceHierarchyType.None, false, (int)FileStream.EntityType.AttachmentEntity, typeof(AttachmentEntity), typeof(AttachmentEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static AttachmentEntity()
		{
		}

		/// <summary> CTor</summary>
		public AttachmentEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AttachmentEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AttachmentEntity</param>
		public AttachmentEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Attachment which data should be fetched into this Attachment object</param>
		public AttachmentEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Attachment which data should be fetched into this Attachment object</param>
		/// <param name="validator">The custom validator object for this AttachmentEntity</param>
		public AttachmentEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AttachmentEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Fsunique .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCFsunique()
		{
			var filter = new PredicateExpression();
			filter.Add(FileStream.HelperClasses.AttachmentFields.Fsunique == this.Fields.GetCurrentValue((int)AttachmentFieldIndex.Fsunique));
 			return filter;
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AttachmentEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AttachmentRelations Relations { get { return _relationsFactory; } }

		/// <summary>The File property of the Entity Attachment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Attachment"."File".<br/>Table field type characteristics (type, precision, scale, length): VarBinary, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.Byte[] File
		{
			get { return (System.Byte[])GetValue((int)AttachmentFieldIndex.File, true); }
			set	{ SetValue((int)AttachmentFieldIndex.File, value); }
		}

		/// <summary>The Fsunique property of the Entity Attachment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Attachment"."FSUnique".<br/>Table field type characteristics (type, precision, scale, length): UniqueIdentifier, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid Fsunique
		{
			get { return (System.Guid)GetValue((int)AttachmentFieldIndex.Fsunique, true); }
			set	{ SetValue((int)AttachmentFieldIndex.Fsunique, value); }
		}

		/// <summary>The Id property of the Entity Attachment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Attachment"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)AttachmentFieldIndex.Id, true); }
			set { SetValue((int)AttachmentFieldIndex.Id, value); }		}

		/// <summary>The MimeType property of the Entity Attachment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Attachment"."MimeType".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 250.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MimeType
		{
			get { return (System.String)GetValue((int)AttachmentFieldIndex.MimeType, true); }
			set	{ SetValue((int)AttachmentFieldIndex.MimeType, value); }
		}

		/// <summary>The OriginalFileName property of the Entity Attachment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Attachment"."OriginalFileName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 250.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String OriginalFileName
		{
			get { return (System.String)GetValue((int)AttachmentFieldIndex.OriginalFileName, true); }
			set	{ SetValue((int)AttachmentFieldIndex.OriginalFileName, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace FileStream
{
	public enum AttachmentFieldIndex
	{
		///<summary>File. </summary>
		File,
		///<summary>Fsunique. </summary>
		Fsunique,
		///<summary>Id. </summary>
		Id,
		///<summary>MimeType. </summary>
		MimeType,
		///<summary>OriginalFileName. </summary>
		OriginalFileName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace FileStream.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Attachment. </summary>
	public partial class AttachmentRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAttachmentRelations
	{

		/// <summary>CTor</summary>
		static StaticAttachmentRelations() { }
	}
}
