//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace FileStream.HelperClasses
{
	/// <summary>Field Creation Class for entity AttachmentEntity</summary>
	public partial class AttachmentFields
	{
		/// <summary>Creates a new AttachmentEntity.File field instance</summary>
		public static EntityField2 File { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AttachmentFieldIndex.File); }}
		/// <summary>Creates a new AttachmentEntity.Fsunique field instance</summary>
		public static EntityField2 Fsunique { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AttachmentFieldIndex.Fsunique); }}
		/// <summary>Creates a new AttachmentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AttachmentFieldIndex.Id); }}
		/// <summary>Creates a new AttachmentEntity.MimeType field instance</summary>
		public static EntityField2 MimeType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AttachmentFieldIndex.MimeType); }}
		/// <summary>Creates a new AttachmentEntity.OriginalFileName field instance</summary>
		public static EntityField2 OriginalFileName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AttachmentFieldIndex.OriginalFileName); }}
	}
	

}