//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using FileStream.FactoryClasses;
using FileStream.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace FileStream.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitAttachmentEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits AttachmentEntity's info objects</summary>
		private void InitAttachmentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(AttachmentFieldIndex), "AttachmentEntity");
			this.AddElementFieldInfo("AttachmentEntity", "File", typeof(System.Byte[]), false, false, false, true,  (int)AttachmentFieldIndex.File, 2147483647, 0, 0);
			this.AddElementFieldInfo("AttachmentEntity", "Fsunique", typeof(System.Guid), false, false, false, false,  (int)AttachmentFieldIndex.Fsunique, 0, 0, 0);
			this.AddElementFieldInfo("AttachmentEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)AttachmentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("AttachmentEntity", "MimeType", typeof(System.String), false, false, false, true,  (int)AttachmentFieldIndex.MimeType, 250, 0, 0);
			this.AddElementFieldInfo("AttachmentEntity", "OriginalFileName", typeof(System.String), false, false, false, true,  (int)AttachmentFieldIndex.OriginalFileName, 250, 0, 0);
		}
	}
}